export const CARD_SPRITE_WIDTH = 1200;
export const CARD_SPRITE_HEIGHT = 747;
export const CARD_NUM_SPRITES_X = 10;
export const CARD_NUM_SPRITES_Y = 4;
export const CARD_WIDTH = CARD_SPRITE_WIDTH / CARD_NUM_SPRITES_X;
export const CARD_HEIGHT = CARD_SPRITE_HEIGHT / CARD_NUM_SPRITES_Y;
